name: build-and-link

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install bun
        run: npm i -g bun

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun lint

      - name: Prettier
        run: bun prettier

      - name: Build
        run: bun run build
